title : De choses et d'autres
author :
  name : Gilles Navarro
  email : blah@email.test
  github : gnavarro77
  url : http://gnavarro77.github.io
  twitter : username
  feedburner : feedname
permalink: /:categories/:year/:month/:day/:title 
production_url : http://gnavarro77.github.io
highlighter: pygments
markdown: kramdown

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
encoding: utf-8

kramdown:
   input: GFM

jekyll-archives:
  enabled:
    - tags
    - categories
  layout: 'monthly_archive'
  permalinks:
    tag: '/:name/'
gems: 
  - jekyll-archives